data_dir = "/var/lib/vector"

[sources.test_file]
    type = "file"
    include = ["/tmp/test_log/*"]

[sinks.test_kafka_sink]
  type = "kafka"
  inputs = ["test_file"]
  bootstrap_servers = ["kafka-1:9091", "kafka-2:9092", "kafka-3:9093"]
  encoding = "json"
  key_field = "user_id"
  topic = "kafka_vector_topic"

[sinks.test_sink]
    type = "file"
    inputs = ["test_file"]
    path = "/tmp/vector-%Y-%m-%d.log"