---
- name: change vector daemon state
  systemd:
    name: vector
    daemon_reload: "{{ vector_daemon_reload }}"
    state: "{{ vector_daemon_state }}"
  when: vector_daemon_state != "reloaded"

- name: reload vector service
  shell: systemctl kill -s HUP --kill-who=main vector.service
  when: vector_daemon_state == "reloaded"