---
- name: download installation binary
  get_url:
    url: https://sh.vector.dev
    dest: /tmp/install-vector.sh
    mode: 0755
    owner: root
    group: root
  
- name: install vector from script
  script: /tmp/install-vector.sh -y

- name: ensure that vector is stopped
  systemd:
    name: vector
    daemon_reload: true
    enabled: no
    state: stopped

- name: configure vector
  include_tasks: configure.yml
  when: vector_initial_config == true