---
- name: stop vector service
  include_tasks: change_state.yml
  vars:
    vector_daemon_state: stopped

- name: reset vector state
  file:
    path: /var/lib/vector
    state: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - absent
    - directory