---
docker_apt_repo: 'deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'

docker_version: "{%if ansible_os_family == 'Debian' %}{{ docker_apt_version }}{% elif ansible_os_family == 'RedHat' %}{{ docker_yum_version }}{% else %}latest{% endif %}"

docker_packages:
  - "docker-{{ docker_edition }}{% if docker_version != 'latest' %}{% if ansible_os_family == 'Debian' %}={% else %}-{% endif %}{{ docker_version }}{% endif %}"
  - "docker-{{ docker_edition }}-cli{% if docker_version != 'latest' %}{% if ansible_os_family == 'Debian' %}={% else %}-{% endif %}{{ docker_version }}{% endif %}"
  - "containerd.io"

docker_compose_download_url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'