---
- name: check current docker-compose version
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: delete docker-compose version if it is different from requested
  file:
    path: '{{ docker_compose_binary_path }}'
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: install docker-compose
  get_url:
    url: '{{ docker_compose_download_url }}'
    dest: '{{ docker_compose_binary_path }}'
    mode: 0755