---
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_ignore_key_error: true
docker_apt_version: latest

docker_yum_version: latest
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo

docker_force_install: true
docker_edition: ce

docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

docker_compose_install: true
docker_compose_version: 1.24.1
docker_compose_binary_path: /usr/local/bin/docker-compose

docker_users:
  - vagrant