docker_network:
  name: kafka_network
  subnet: 172.3.28.0/24
telegraf_config:
  input_plugins:
    - name: docker
      attributes:
        endpoint: "unix:///var/run/docker.sock"  
        gather_services: false
        container_name_include: []
        container_name_exclude: []
        timeout: "5s"
        total: false
    - name: jolokia2_agent
      attributes:
        urls: ["http://kafka-1:8778/jolokia", "http://kafka-2:8778/jolokia", "http://kafka-3:8778/jolokia"]
        name_prefix: "kafka_"
      metrics:
        - name: "topic-size-bytes"
          mbean: "kafka.log:type=Log,name=Size,topic=*,partition=*"
          paths: ["Value"]
          field_prefix: "$1."
          tag_keys: ["topic"]
        - name: "messages-in"
          mbean: "kafka.server:name=MessagesInPerSec,topic=*,type=BrokerTopicMetrics"
          paths: ["OneMinuteRate", "FiveMinuteRate", "FifteenMinuteRate", "Count"]
          field_prefix: "$1."
          tag_keys: ["topic"]
  output_plugins:
    - name: file
      attributes:
        files: ["/tmp/telegraf/telegraf.out"]
        rotation_interval: "5m"
        rotation_max_archives: 3
        data_format: "json"
    - name: influxdb
      attributes:
        urls: ["http://monitoring.example.test:8086"]
        database: "telegraf"
        skip_database_creation: false
        timeout: "5s"
        user_agent: "telegraf"