---
# tasks file for fluentbit_config
- name: check that fluent-bit directory exists
  file:
    path: /opt/fluent-bit
    state: directory
    mode: 0644
    owner: root
    group: root

- name: configure fluent-bit
  template:
    src: fluent-bit.conf.j2
    dest: /opt/fluent-bit/fluent-bit.conf
    mode: 0644