---
- name: clone flog from git
  git:
    repo: "{{ flog_repo_url }}"
    dest: "{{ flog_repo_dest }}"
    version: "{{ flog_repo_branch }}"

- name: build flog docker image
  docker_image:
    name: "{{ flog_image_name }}"
    build:
      path: "{{ flog_repo_dest }}"
      dockerfile: Dockerfile
      nocache: true
    tag: "{{ flog_image_tag }}"
    source: build
    state: present

- name: list dangling docker image ids
  shell: docker images -f "dangling=true" -q
  register: docker_dangling_ids
  when: (flog_image_clean_cache | bool)

- name: debug
  debug:
    msg: "{{ docker_dangling_ids }}"
  when: (flog_image_clean_cache | bool)

- name: remove flog docker image cache
  shell: "docker rmi {{ docker_dangling_ids.stdout_lines | join(' ') }}"
  when: (flog_image_clean_cache | bool)
    and (docker_dangling_ids.stdout_lines is defined)
    and (docker_dangling_ids.stdout_lines | bool)

- name: remove flog repository
  file:
    path: "{{ flog_repo_dest }}/"
    state: absent
  when: (flog_repo_cleanup | bool)