---
- name: check that python-pip is installed
  shell: pip -V
  register: pip_installed_version
  ignore_errors: true

- name: install pip if it is not installed
  package:
    name: python-pip
    state: present
  when: pip_installed_version.rc != 0

- name: upgrade pip to the latest version
  pip:
    name: pip
    state: latest
  when: pip_upgrade == true

- name: clone collectd docker plugin
  git:
    repo: https://github.com/lebauce/docker-collectd-plugin.git
    dest: /usr/share/collectd/docker-collectd-plugin
    version: master
    bare: false
    clone: true

- name: set up collectd docker plugin
  pip:
    chdir: /usr/share/collectd/docker-collectd-plugin
    requirements: requirements.txt
    state: present