---
# tasks file for collectd
- name: ensure that collectd is installed
  package:
    name: collectd
    state: present

- name: ensure that collectd service is stopped
  systemd:
    name: collectd
    daemon_reload: true
    enabled: false
    state: stopped

- name: install docker plugin
  include_tasks: install_docker_plugin.yml
  when: collectd_install_docker_plugin == true

- name: copy collectd configuration to remote host
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
  notify: restart collectd