---
- hosts: all
  remote_user: vagrant
  become: true
  vars:
    fluentbit:
      - fluentbit
    applications:
      - fluent-bit
    input_plugins:
      - name: docker
        attributes:
          endpoint: "unix:///var/run/docker.sock"  
          gather_services: false
          container_name_include: []
          container_name_exclude: []
          timeout: "5s"
          total: false
      - name: statsd
        attributes:
          protocol: "udp"
          max_tcp_connections: 250
          tcp_keep_alive: false
          service_address: ":8125"
          delete_gauges: false
          metric_separator: "_"
      - name: http
        attributes:
          urls: ["http://fluent-bit:2020/api/v1/metrics"]
          data_format: "json"
  roles:
    - "{{ fluentbit[0] }}_config"
    - telegraf_config
    - deploy
    - gantsign.golang