---
- hosts: all
  remote_user: vagrant
  become: true
  vars:
    applications:
      - monitoring
      - kafka
    input_plugins:
      - name: docker
        attributes:
          endpoint: "unix:///var/run/docker.sock"  
          gather_services: false
          container_name_include: []
          container_name_exclude: []
          timeout: "5s"
          total: false
      - name: jolokia2_agent
        attributes:
          urls: ["http://kafka-1:8778/jolokia", "http://kafka-2:8778/jolokia", "http://kafka-3:8778/jolokia"]
          name_prefix: "kafka_"
        metrics:
          - name: "topic-size-bytes"
            mbean: "kafka.log:type=Log,name=Size,topic=*,partition=*"
            paths: ["Value"]
            field_prefix: "$1."
            tag_keys: ["topic"]

          - name: "messages-in"
            mbean: "kafka.server:name=MessagesInPerSec,topic=*,type=BrokerTopicMetrics"
            paths: ["OneMinuteRate", "FiveMinuteRate", "FifteenMinuteRate", "Count"]
            field_prefix: "$1."
            tag_keys: ["topic"]
  roles:
    - deploy
