---
# handlers file for telegraf_config
- name: check telegraf config file
  shell: docker exec telegraf bash -c "telegraf --test >/dev/null 2>&1"
  listen: "update telegraf config"

- name: restart telegraf process
  shell: docker restart telegraf
  listen: "update telegraf config"